server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: productService
          uri: http://localhost:8081/
          predicates:
            - Path=/product/**
        - id: userService
          uri: http://localhost:8082/
          predicates:
            - Path=/user/**
        - id: companyService
          uri: http://localhost:8083/
          predicates:
            - Path=/company/**
        - id: notificationService
          uri: http://localhost:8084/
          predicates:
            - Path=/notification/**
        - id: basketService
          uri: http://localhost:8085/
          predicates:
            - Path=/cart/**
        - id: offerService
          uri: http://localhost:8086/
          predicates:
            - Path=/offer/**

